export const UserDummy = [
  {
    email: "adit.budi@example.com",
    password: "passwordA",
    firstName: "Adit",
    lastName: "Budi",
    color: 0,
    profileSetup: true,
    status: false,
  },
  {
    email: "beni.citra@example.com",
    password: "passwordB",
    firstName: "Beni",
    lastName: "Citra",
    color: 1,
    profileSetup: true,
    status: false,
  },
  {
    email: "cici.dika@example.com",
    password: "passwordC",
    firstName: "Cici",
    lastName: "Dika",
    color: 2,
    profileSetup: true,
    status: false,
  },
  {
    email: "deni.elvi@example.com",
    password: "passwordD",
    firstName: "Deni",
    lastName: "Elvi",
    color: 3,
    profileSetup: true,
    status: false,
  },
  {
    email: "elma.fais@example.com",
    password: "passwordE",
    firstName: "Elma",
    lastName: "Fais",
    color: 0,
    profileSetup: true,
    status: false,
  },
  {
    email: "fina.gani@example.com",
    password: "passwordF",
    firstName: "Fina",
    lastName: "Gani",
    color: 1,
    profileSetup: true,
    status: false,
  },
  {
    email: "gita.hani@example.com",
    password: "passwordG",
    firstName: "Gita",
    lastName: "Hani",
    color: 2,
    profileSetup: true,
    status: false,
  },
  {
    email: "hadi.indi@example.com",
    password: "passwordH",
    firstName: "Hadi",
    lastName: "Indi",
    color: 3,
    profileSetup: true,
    status: false,
  },
  {
    email: "irsa.jaka@example.com",
    password: "passwordI",
    firstName: "Irsa",
    lastName: "Jaka",
    color: 0,
    profileSetup: true,
    status: false,
  },
  {
    email: "janu.kimi@example.com",
    password: "passwordJ",
    firstName: "Janu",
    lastName: "Kimi",
    color: 1,
    profileSetup: true,
    status: false,
  },
  {
    email: "kira.lian@example.com",
    password: "passwordK",
    firstName: "Kira",
    lastName: "Lian",
    color: 2,
    profileSetup: true,
    status: false,
  },
  {
    email: "lina.mira@example.com",
    password: "passwordL",
    firstName: "Lina",
    lastName: "Mira",
    color: 3,
    profileSetup: true,
    status: false,
  },
  {
    email: "maya.nina@example.com",
    password: "passwordM",
    firstName: "Maya",
    lastName: "Nina",
    color: 0,
    profileSetup: true,
    status: false,
  },
  {
    email: "nana.opik@example.com",
    password: "passwordN",
    firstName: "Nana",
    lastName: "Opik",
    color: 1,
    profileSetup: true,
    status: false,
  },
  {
    email: "okta.puja@example.com",
    password: "passwordO",
    firstName: "Okta",
    lastName: "Puja",
    color: 2,
    profileSetup: true,
    status: false,
  },
  {
    email: "pino.qila@example.com",
    password: "passwordP",
    firstName: "Pino",
    lastName: "Qila",
    color: 3,
    profileSetup: true,
    status: false,
  },
  {
    email: "qori.rima@example.com",
    password: "passwordQ",
    firstName: "Qori",
    lastName: "Rima",
    color: 0,
    profileSetup: true,
    status: false,
  },
  {
    email: "rudi.siti@example.com",
    password: "passwordR",
    firstName: "Rudi",
    lastName: "Siti",
    color: 1,
    profileSetup: true,
    status: false,
  },
  {
    email: "sari.tian@example.com",
    password: "passwordS",
    firstName: "Sari",
    lastName: "Tian",
    color: 2,
    profileSetup: true,
    status: false,
  },
  {
    email: "tina.ulan@example.com",
    password: "passwordT",
    firstName: "Tina",
    lastName: "Ulan",
    color: 3,
    profileSetup: true,
    status: false,
  },
  {
    email: "udin.vira@example.com",
    password: "passwordU",
    firstName: "Udin",
    lastName: "Vira",
    color: 0,
    profileSetup: true,
    status: false,
  },
  {
    email: "vina.wati@example.com",
    password: "passwordV",
    firstName: "Vina",
    lastName: "Wati",
    color: 1,
    profileSetup: true,
    status: false,
  },
  {
    email: "widi.xena@example.com",
    password: "passwordW",
    firstName: "Widi",
    lastName: "Xena",
    color: 2,
    profileSetup: true,
    status: false,
  },
  {
    email: "xena.yani@example.com",
    password: "passwordX",
    firstName: "Xena",
    lastName: "Yani",
    color: 3,
    profileSetup: true,
    status: false,
  },
  {
    email: "yana.zara@example.com",
    password: "passwordY",
    firstName: "Yana",
    lastName: "Zara",
    color: 0,
    profileSetup: true,
    status: false,
  },
  {
    email: "zaki.adil@example.com",
    password: "passwordZ",
    firstName: "Zaki",
    lastName: "Adil",
    color: 1,
    profileSetup: true,
    status: false,
  },
];
